
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.aiwen.wfgwechat.entity.pojo  # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true #大于最大也显示最后一页  小于最小也显示第一页
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
  level:
    com.aiwen.wfgwechat.dao: DEBUG



fdfs:
  so-timeout: 5000
  connect-timeout: 5000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 47.95.6.0:22122 #TrackerList参数,支持多个
  pool:
      max-total: 100
      max-wait-millis: 60
spring:
  jmx:
    default-domain: project2
  profiles:
    active: online

